

#ifndef __CUSTOM_MEMORYDEVICE__
#define __CUSTOM_MEMORYDEVICE__



#define BOARD_ID                MT6582_EVB

#define CS_PART_NUMBER[0]       H9TP32A8JDACPR_KGM
#define CS_PART_NUMBER[1]       KMK5U000VM_B309

#endif /* __CUSTOM_MEMORYDEVICE__ */
